# Generated by Django 6.0.3 on 2026-04-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the event.')),
                ('event_type', models.CharField(choices=[('game', 'Game Day'), ('private_party', 'Private Party'), ('live_music', 'Live Music'), ('holiday', 'Holiday'), ('other', 'Other')], default='game', help_text='Type of event. Controls labeling and future type-specific behavior.', max_length=20)),
                ('label', models.CharField(blank=True, help_text="Optional display label shown on the site, e.g. 'Pirates vs. Cubs' or 'Private Event — Patio Reserved'. Leave blank to use the event type display name.", max_length=200)),
                ('team', models.CharField(blank=True, choices=[('pirates', 'Pittsburgh Pirates'), ('steelers', 'Pittsburgh Steelers'), ('penguins', 'Pittsburgh Penguins'), ('other', 'Other')], help_text='Relevant for game day events only.', max_length=20)),
                ('game_time', models.TimeField(blank=True, help_text='Start time of the game or event. Used to calculate when limited menu mode activates (see limited_menu_lead_hours). Leave blank to activate limited menu all day.', null=True)),
                ('limited_menu_lead_hours', models.PositiveIntegerField(default=2, help_text='How many hours before game_time to activate limited menu mode. Default is 2 hours. Ignored if game_time is blank (all-day).')),
                ('limited_menu', models.BooleanField(default=True, help_text="Activate limited menu mode for this event. Uncheck for events that don't restrict the menu (e.g. live music with full service).")),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to disable this event without deleting it — useful for cancelled or rescheduled games.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Day',
                'verbose_name_plural': 'Event Days',
                'ordering': ['date', 'game_time'],
                'indexes': [models.Index(fields=['date', 'is_active'], name='events_even_date_0bb813_idx')],
            },
        ),
    ]
