# Generated by Django 6.0.3 on 2026-05-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventday',
            name='home_away',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('away', 'Away')], help_text='Home or away game. Away games use full menu.', max_length=4),
        ),
    ]
