# Generated by Django 6.0.3 on 2026-05-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_add_home_away_to_eventday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventday',
            name='team',
            field=models.CharField(blank=True, choices=[('pirates', 'Pittsburgh Pirates'), ('steelers', 'Pittsburgh Steelers'), ('pitt', 'Pittsburgh Panthers'), ('penguins', 'Pittsburgh Penguins'), ('other', 'Other')], help_text='Relevant for game day events only.', max_length=20),
        ),
    ]
