# Generated by Django 6.0.3 on 2026-04-02 23:17

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('menu_type', models.CharField(choices=[('food', 'Food'), ('drinks', 'Drinks'), ('combined', 'Combined (Food & Drinks)'), ('promo', 'Promotion')], default='promo', help_text="Controls how this menu is rendered. 'Combined' shows Food and Drinks tabs. 'Promotion' enables color scheme and homepage display.", max_length=10)),
                ('is_default', models.BooleanField(default=False, help_text='Marks this as the default menu for its type. One default per menu_type. The default combined/food/drinks menu is what renders on the main menu pages.')),
                ('start_date', models.DateField(blank=True, help_text='Date this menu becomes visible (leave blank for immediate).', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Date this menu expires (leave blank for no expiry).', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Master switch — uncheck to hide regardless of dates.')),
                ('show_on_homepage', models.BooleanField(default=False, help_text='Show this menu as a block on the home page. Typically used for promotions and featured specials.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'ordering': ['menu_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category_type', models.CharField(choices=[('food', 'Food'), ('drinks', 'Drinks')], default='food', help_text='Food or Drinks — used by combined menus to split categories into the correct tab.', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Default display order within this category type. Per-menu ordering is set on MenuCategoryAssignment.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive categories are hidden everywhere regardless of menu assignment.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Menu Category',
                'verbose_name_plural': 'Menu Categories',
                'ordering': ['category_type', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PromoColorScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal label, e.g. 'Black & Gold', 'Holiday Red'.", max_length=100, unique=True)),
                ('primary_color', models.CharField(blank=True, help_text='Main color (hex, e.g. #ffb612).', max_length=30)),
                ('accent_color', models.CharField(blank=True, help_text='Secondary / highlight color (hex).', max_length=30)),
                ('text_color', models.CharField(blank=True, help_text='Text color (hex).', max_length=30)),
                ('bg_color', models.CharField(blank=True, help_text='Background color (hex).', max_length=30)),
                ('is_default', models.BooleanField(default=False, help_text='Use this scheme when a menu has no scheme assigned. Saving a new default clears the flag on the previous one.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Color Scheme',
                'verbose_name_plural': 'Color Schemes',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PromoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_primary_color', models.CharField(blank=True, max_length=30)),
                ('promo_accent_color', models.CharField(blank=True, max_length=30)),
                ('promo_text_color', models.CharField(blank=True, max_length=30)),
                ('promo_bg_color', models.CharField(blank=True, max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promo Settings',
                'verbose_name_plural': 'Promo Settings',
            },
        ),
        migrations.CreateModel(
            name='MenuCategoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which this category appears within this menu.')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_assignments', to='menu.menucategory')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_category_assignments', to='menu.menu')),
            ],
            options={
                'verbose_name': 'Menu Category Assignment',
                'verbose_name_plural': 'Menu Category Assignments',
                'ordering': ['display_order'],
                'unique_together': {('menu', 'category')},
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='menus', through='menu.MenuCategoryAssignment', to='menu.menucategory'),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Detailed description shown in the item modal.')),
                ('short_description', models.CharField(blank=True, help_text='Brief description for menu listings.', max_length=300)),
                ('price_display', models.CharField(choices=[('price', 'Show Price'), ('market', 'Market Price (MP)'), ('hidden', 'Hide Price')], default='price', help_text="'Show Price' displays the price field. 'Market Price' shows 'MP'. 'Hide Price' shows nothing — useful for drinks with no listed price.", max_length=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Base price. Leave blank for Market Price or Hidden.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional sale price. Shown instead of base price when set.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('has_variations', models.BooleanField(default=False, help_text='Check if this item has multiple size/quantity options.')),
                ('has_addons', models.BooleanField(default=False, help_text='Check if this item has add-on options.')),
                ('dietary_type', models.CharField(choices=[('none', 'None'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('gluten_free', 'Gluten Free'), ('dairy_free', 'Dairy Free')], default='none', max_length=20)),
                ('is_gluten_free', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_dairy_free', models.BooleanField(default=False)),
                ('is_nut_free', models.BooleanField(default=False)),
                ('contains_shellfish', models.BooleanField(default=False)),
                ('allergen_info', models.TextField(blank=True, help_text='Additional allergen warnings.')),
                ('spice_level', models.IntegerField(choices=[(0, 'Not Spicy'), (1, 'Mild'), (2, 'Medium'), (3, 'Hot'), (4, 'Extra Hot')], default=0)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('preparation_time', models.PositiveIntegerField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Spotlight this item on the home page and menu featured sections. Independent of any promotion.')),
                ('is_chef_special', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('is_seasonal', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True, help_text='Global availability switch. Overrides all menu placements.')),
                ('available_from', models.TimeField(blank=True, null=True)),
                ('available_until', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_featured', 'is_available'], name='menu_menuit_is_feat_95356a_idx')],
            },
        ),
        migrations.CreateModel(
            name='MenuSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order within the parent category (lower numbers first).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='The category this sub-category belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='menu.menucategory')),
            ],
            options={
                'verbose_name': 'Menu Sub-Category',
                'verbose_name_plural': 'Menu Sub-Categories',
                'ordering': ['category__order', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='color_scheme',
            field=models.ForeignKey(blank=True, help_text='Color scheme for this menu. Leave blank to use the default scheme.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus', to='menu.promocolorscheme'),
        ),
        migrations.CreateModel(
            name='MenuItemAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item Add-on',
                'verbose_name_plural': 'Menu Item Add-ons',
                'ordering': ['order', 'price'],
                'unique_together': {('menu_item', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MenuItemVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item Variation',
                'verbose_name_plural': 'Menu Item Variations',
                'ordering': ['order', 'price'],
                'unique_together': {('menu_item', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MenuItemCategoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within this category. Independent per placement.')),
                ('override_price', models.DecimalField(blank=True, decimal_places=2, help_text="Price for this placement only — overrides the item's base price. Used for Happy Hour, specials pricing, etc. Leave blank to use the item's standard price.", max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('note', models.CharField(blank=True, help_text="Short callout shown on this item in this placement only, e.g. 'Half price during Happy Hour' or 'Limited time!'.", max_length=200)),
                ('available_game_day', models.BooleanField(default=False, help_text='Include this item when the venue is in limited menu mode (game days, busy events). Defaults to False — opt in explicitly.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this item from this category without removing the assignment.')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_assignments', to='menu.menucategory')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_assignments', to='menu.menuitem')),
                ('subcategory', models.ForeignKey(blank=True, help_text='Optional sub-grouping within the category (e.g. On Tap, Bottles & Cans).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_assignments', to='menu.menusubcategory')),
            ],
            options={
                'verbose_name': 'Item Category Assignment',
                'verbose_name_plural': 'Item Category Assignments',
                'ordering': ['category__order', 'subcategory__order', 'order'],
                'unique_together': {('menu_item', 'category')},
            },
        ),
    ]
