# Generated by Django 5.0.14 on 2026-02-17 02:06

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, help_text='Optional icon for the category', null=True, upload_to='menu/category_icons/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which categories appear (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Display this category on the menu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Menu Category',
                'verbose_name_plural': 'Menu Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Detailed description of the dish')),
                ('short_description', models.CharField(blank=True, help_text='Brief description for menu listings', max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional discounted price', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('image', models.ImageField(blank=True, help_text='Primary image of the dish', null=True, upload_to='menu/items/')),
                ('image_alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=200)),
                ('dietary_type', models.CharField(choices=[('none', 'None'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('gluten_free', 'Gluten Free'), ('dairy_free', 'Dairy Free')], default='none', max_length=20)),
                ('is_gluten_free', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_dairy_free', models.BooleanField(default=False)),
                ('is_nut_free', models.BooleanField(default=False)),
                ('contains_shellfish', models.BooleanField(default=False)),
                ('allergen_info', models.TextField(blank=True, help_text='Additional allergen warnings')),
                ('spice_level', models.IntegerField(choices=[(0, 'Not Spicy'), (1, 'Mild'), (2, 'Medium'), (3, 'Hot'), (4, 'Extra Hot')], default=0, help_text='Spiciness level of the dish')),
                ('calories', models.PositiveIntegerField(blank=True, help_text='Approximate calorie count', null=True)),
                ('preparation_time', models.PositiveIntegerField(blank=True, help_text='Preparation time in minutes', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this item prominently')),
                ('is_chef_special', models.BooleanField(default=False, help_text="Mark as chef's special")),
                ('is_new', models.BooleanField(default=False, help_text='Mark as new item')),
                ('is_seasonal', models.BooleanField(default=False, help_text='Seasonal availability')),
                ('is_available', models.BooleanField(default=True, help_text='Currently available for order')),
                ('available_from', models.TimeField(blank=True, help_text='Available from this time (optional)', null=True)),
                ('available_until', models.TimeField(blank=True, help_text='Available until this time (optional)', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order within category (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menucategory')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['category__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='menu/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item Image',
                'verbose_name_plural': 'Menu Item Images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['category', 'order'], name='menu_menuit_categor_b4511b_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['is_featured', 'is_available'], name='menu_menuit_is_feat_95356a_idx'),
        ),
    ]
