# Generated by Django 6.0.3 on 2026-04-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='show_disclaimer',
            field=models.BooleanField(default=False, help_text='Show the menu footer disclaimer at the bottom of this category section.'),
        ),
    ]
