# Generated by Django 5.0.14 on 2026-03-03 18:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='prices_vary',
            field=models.BooleanField(default=False, help_text='Check if this item has no single fixed price (e.g., market price or see variations). Hides the price field on the menu.'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Base price or price for standard size. Leave blank if 'Prices Vary' is checked.", max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.CreateModel(
            name='MenuSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which sub-categories appear within their category (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Display this sub-category on the menu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='The category this sub-category belongs to (e.g., Beer)', on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='menu.menucategory')),
            ],
            options={
                'verbose_name': 'Menu Sub-Category',
                'verbose_name_plural': 'Menu Sub-Categories',
                'ordering': ['category__menu_type__order', 'category__order', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Optional sub-category (e.g., Bottled, Draft). Leave blank if not applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='menu.menusubcategory'),
        ),
    ]
