# Generated by Django 5.0.14 on 2026-02-17 03:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_add_menuitemvariation'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='has_addons',
            field=models.BooleanField(default=False, help_text='Check if this item has add-on options'),
        ),
        migrations.CreateModel(
            name='MenuItemAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Addon name (e.g., 'Chicken', 'Steak', etc.)", max_length=100)),
                ('description', models.CharField(blank=True, help_text='Optional description of this add-on', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default/recommended option?')),
                ('is_available', models.BooleanField(default=True, help_text='Is this add-on currently available?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item Add-on',
                'verbose_name_plural': 'Menu Item Add-ons',
                'ordering': ['order', 'price'],
                'unique_together': {('menu_item', 'name')},
            },
        ),
    ]
