# Generated by Django 6.0.3 on 2026-04-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menucategory_show_disclaimer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='start_date',
        ),
        migrations.AddField(
            model_name='menu',
            name='active_from',
            field=models.DateTimeField(blank=True, help_text='Date and time this becomes visible. Leave blank for immediate.', null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='active_until',
            field=models.DateTimeField(blank=True, help_text='Date and time this expires. Leave blank for no expiry.', null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='days_of_week',
            field=models.JSONField(blank=True, default=list, help_text='Days this is active. Leave empty for every day. Uses Python weekday integers: 0=Monday … 6=Sunday.'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Master switch. Uncheck to hide regardless of scheduled dates.'),
        ),
    ]
