# Generated by Django 6.0.3 on 2026-04-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_menu_end_date_remove_menu_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='active_from',
            field=models.DateTimeField(blank=True, help_text='Date and time this becomes visible. Leave blank for immediate.', null=True),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='active_until',
            field=models.DateTimeField(blank=True, help_text='Date and time this expires. Leave blank for no expiry.', null=True),
        ),
        migrations.AddField(
            model_name='menusubcategory',
            name='active_from',
            field=models.DateTimeField(blank=True, help_text='Date and time this becomes visible. Leave blank for immediate.', null=True),
        ),
        migrations.AddField(
            model_name='menusubcategory',
            name='active_until',
            field=models.DateTimeField(blank=True, help_text='Date and time this expires. Leave blank for no expiry.', null=True),
        ),
    ]
