# Generated by Django 5.0.14 on 2026-03-03 19:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menuitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='prices_vary',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='price_display',
            field=models.CharField(choices=[('price', 'Show Price'), ('market', 'Market Price (MP)'), ('hidden', 'Hide Price')], default='price', help_text="'Show Price' displays the price field. 'Market Price' shows 'MP' on the menu. 'Hide Price' shows nothing — useful when price isn't relevant for web display.", max_length=10),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base price or price for standard size. Leave blank for Market Price or Hidden.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
