# Generated by Django 6.0.3 on 2026-04-07 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menucategory_active_from_menucategory_active_until_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucategory',
            name='active_from',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='active_until',
        ),
        migrations.RemoveField(
            model_name='menusubcategory',
            name='active_from',
        ),
        migrations.RemoveField(
            model_name='menusubcategory',
            name='active_until',
        ),
    ]
