# Generated by Django 5.0.14 on 2026-03-06 19:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_menuitem_prices_vary_menuitem_price_display_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, help_text='Date this promotion becomes visible (leave blank for immediate)', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Date this promotion expires (leave blank for no expiry)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Master switch — uncheck to hide regardless of dates')),
                ('promo_primary_color', models.CharField(blank=True, help_text='Override: main promo color for this promotion (hex)', max_length=30)),
                ('promo_accent_color', models.CharField(blank=True, help_text='Override: secondary promo color for this promotion (hex)', max_length=30)),
                ('promo_text_color', models.CharField(blank=True, help_text="Override: text color for this promotion's component (hex)", max_length=30)),
                ('promo_bg_color', models.CharField(blank=True, help_text="Override: background color for this promotion's component (hex)", max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Menu Promotion',
                'verbose_name_plural': 'Menu Promotions',
                'ordering': ['start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PromoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_primary_color', models.CharField(blank=True, help_text='Global default: main promo color (hex, e.g. #ffb612)', max_length=30)),
                ('promo_accent_color', models.CharField(blank=True, help_text='Global default: secondary promo color (hex)', max_length=30)),
                ('promo_text_color', models.CharField(blank=True, help_text='Global default: text color within promo components (hex)', max_length=30)),
                ('promo_bg_color', models.CharField(blank=True, help_text='Global default: background color for promo components (hex)', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promo Settings',
                'verbose_name_plural': 'Promo Settings',
            },
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='available_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='available_until',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='calories',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_chef_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_seasonal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='preparation_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuitemaddon',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='menuitemaddon',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menuitemaddon',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menuitemaddon',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitemaddon',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menuitemvariation',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='menuitemvariation',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menuitemvariation',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menuitemvariation',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitemvariation',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menuitemvariation',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuitemvariation',
            name='size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='MenuPromotionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_price', models.DecimalField(blank=True, decimal_places=2, help_text="Promotional price — overrides the item's standard price when set", max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within this promotion (lower numbers first)')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_entries', to='menu.menuitem')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_items', to='menu.menupromotion')),
            ],
            options={
                'verbose_name': 'Promotion Item',
                'verbose_name_plural': 'Promotion Items',
                'ordering': ['order', 'menu_item__name'],
                'unique_together': {('promotion', 'menu_item')},
            },
        ),
        migrations.AddField(
            model_name='menupromotion',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='promotions', through='menu.MenuPromotionItem', to='menu.menuitem'),
        ),
    ]
