# Generated by Django 6.0.3 on 2026-04-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_menucategory_active_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='days_of_week',
            field=models.JSONField(blank=True, default=list, help_text='Days this is active. Leave empty for every day. Uses Python weekday integers: 0=Monday … 6=Sunday.'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='available_from',
            field=models.TimeField(blank=True, help_text='Time of day this item becomes available (e.g. 11:00 for 11am). Leave blank for no restriction.', null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='available_until',
            field=models.TimeField(blank=True, help_text='Time of day this item stops being available (e.g. 16:00 for 4pm). Leave blank for no restriction.', null=True),
        ),
    ]
