# Generated by Django 5.0.14 on 2026-03-16 18:55

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menupromotion_promosettings_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menupromotionitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='menupromotionitem',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Description. Auto-filled from the linked item if left blank.'),
        ),
        migrations.AddField(
            model_name='menupromotionitem',
            name='name',
            field=models.CharField(blank=True, help_text='Item name. Auto-filled from the linked item if left blank.', max_length=200),
        ),
        migrations.AddField(
            model_name='menupromotionitem',
            name='note',
            field=models.CharField(blank=True, help_text="Short callout shown on the item, e.g. 'Limited time!' or 'While supplies last'.", max_length=200),
        ),
        migrations.AlterField(
            model_name='menupromotionitem',
            name='menu_item',
            field=models.ForeignKey(blank=True, help_text='Link to an existing menu item, or leave blank to enter details below.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_entries', to='menu.menuitem'),
        ),
        migrations.AlterField(
            model_name='menupromotionitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menupromotionitem',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Promotional price — overrides the item's standard price when set.", max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
