# Generated by Django 5.0.14 on 2026-03-20 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_menupromotionitem_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoColorScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal label shown in the admin, e.g. 'Black & Gold', 'Holiday Red'", max_length=100, unique=True)),
                ('primary_color', models.CharField(blank=True, help_text='Main promo color (hex, e.g. #ffb612)', max_length=30)),
                ('accent_color', models.CharField(blank=True, help_text='Secondary / highlight color (hex)', max_length=30)),
                ('text_color', models.CharField(blank=True, help_text='Text color within promo components (hex)', max_length=30)),
                ('bg_color', models.CharField(blank=True, help_text='Background color for promo components (hex)', max_length=30)),
                ('is_default', models.BooleanField(default=False, help_text='Use this scheme when a promotion has no scheme assigned. Saving a new default automatically clears the flag on the previous one.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promo Color Scheme',
                'verbose_name_plural': 'Promo Color Schemes',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='menupromotion',
            name='promo_accent_color',
        ),
        migrations.RemoveField(
            model_name='menupromotion',
            name='promo_bg_color',
        ),
        migrations.RemoveField(
            model_name='menupromotion',
            name='promo_primary_color',
        ),
        migrations.RemoveField(
            model_name='menupromotion',
            name='promo_text_color',
        ),
        migrations.AddField(
            model_name='menupromotion',
            name='color_scheme',
            field=models.ForeignKey(blank=True, help_text='Color scheme for this promotion. Leave blank to use the default scheme.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='menu.promocolorscheme'),
        ),
    ]
