# Generated by Django 6.0.3 on 2026-04-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_menuitem_days_of_week_alter_menuitem_available_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='show_on_homepage',
        ),
        migrations.AddField(
            model_name='menu',
            name='homepage_slot',
            field=models.CharField(choices=[('none', 'None'), ('slot_1', 'Homepage Slot 1 (left)'), ('slot_2', 'Homepage Slot 2 (right)')], default='none', help_text='Assign this promo menu to a homepage display slot. Slot 1 appears left of the hero banner, Slot 2 appears right. Only one menu should occupy each slot at a time.', max_length=10),
        ),
    ]
