# Generated by Django 5.0.14 on 2026-03-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_promocolorscheme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menupromotion',
            name='show_on_homepage',
            field=models.BooleanField(default=True, help_text='Promoted on the home page'),
        ),
    ]
