# Generated by Django 5.0.14 on 2026-03-21 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_menupromotion_show_on_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menupromotion',
            name='show_on_homepage',
            field=models.BooleanField(default=False, help_text='Promoted on the home page'),
        ),
    ]
