# Generated by Django 6.0.3 on 2026-05-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_colorscheme_move_to_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
