# Generated by Django 6.0.3 on 2026-03-26 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_menupromotion_show_on_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucategory',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='image_alt_text',
        ),
        migrations.DeleteModel(
            name='MenuItemImage',
        ),
    ]
