# Generated by Django 6.0.3 on 2026-05-24 20:29

import apps.menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_menuitem_image_menuitem_image_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.menu.models.MenuItemUpload()),
        ),
    ]
