# Generated by Django 6.0.3 on 2026-05-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='role',
            field=models.CharField(choices=[('none', 'No special role'), ('default_food', 'Default Food Menu'), ('default_drinks', 'Default Drinks Menu'), ('event_food', 'Event Food Menu'), ('event_drinks', 'Event Drinks Menu')], default='none', help_text="Functional role used by views to select the correct menu. Only one menu may hold each non-'none' role at a time — assigning a role here automatically removes it from any other menu.", max_length=20),
        ),
    ]
