# Generated by Django 6.0.3 on 2026-05-27 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_menu_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitemcategoryassignment',
            name='available_game_day',
        ),
    ]
