# Generated by Django 6.0.3 on 2026-05-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_remove_menuitemcategoryassignment_available_game_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Legacy flag — the active menu is now selected by role, not is_default. Leave unchecked for new menus.'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_type',
            field=models.CharField(choices=[('food', 'Food'), ('drinks', 'Drinks'), ('promo', 'Promotion')], default='promo', help_text='Food or Drinks for role-assigned menus. Promotion enables color scheme and homepage display.', max_length=10),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='category_type',
            field=models.CharField(choices=[('food', 'Food'), ('drinks', 'Drinks')], default='food', help_text='Food or Drinks — used to determine which menu this category belongs to (food or drinks).', max_length=10),
        ),
    ]
