# Generated by Django 6.0.3 on 2026-05-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_alter_menu_is_default_alter_menu_menu_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Optional background image for this category section on the menu page. When set, the image fills the section with a dark overlay for text legibility. Leave blank for the standard alternating background.', null=True, upload_to='menu_categories/'),
        ),
    ]
