# Generated by Django 6.0.3 on 2026-05-27 20:10
# Hand-edited: replaced AlterField for background_image with RemoveField+AddField
# because PostgreSQL cannot ALTER a varchar/ImageField column directly to bigint (FK).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('menu', '0015_add_menucategory_background_image'),
    ]

    operations = [
        # MenuItem.media_item: new FK to MediaItem (additive — legacy image field kept)
        migrations.AddField(
            model_name='menuitem',
            name='media_item',
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    'Link to a media library item. Overrides the direct image upload above. '
                    'Use this for images already in the media library.'
                ),
                limit_choices_to={'owner_type': 'staff'},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='menu_items',
                to='media.mediaitem',
            ),
        ),

        # MenuCategory.background_image: ImageField → FK to MediaItem
        migrations.RemoveField(
            model_name='menucategory',
            name='background_image',
        ),
        migrations.AddField(
            model_name='menucategory',
            name='background_image',
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    'Optional background image for this category section on the menu page. '
                    'When set, the image fills the section with a dark overlay for text '
                    'legibility. Leave blank for the standard alternating background.'
                ),
                limit_choices_to={'owner_type': 'staff'},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='menu_category_backgrounds',
                to='media.mediaitem',
            ),
        ),
    ]
