# Generated by Django 6.0.3 on 2026-05-27 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('menu', '0016_menuitem_media_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='image_alt',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='media_item',
        ),
        migrations.CreateModel(
            name='MenuItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as the primary image for this item. Only one image per item may be primary — saving a new primary automatically demotes the previous one.')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('media_item', models.ForeignKey(limit_choices_to={'owner_type': 'staff'}, on_delete=django.db.models.deletion.PROTECT, related_name='menu_item_images', to='media.mediaitem')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item Image',
                'verbose_name_plural': 'Menu Item Images',
                'ordering': ['display_order'],
                'unique_together': {('menu_item', 'media_item')},
            },
        ),
    ]
