# Generated by Django 6.0.3 on 2026-05-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_remove_menuitem_image_remove_menuitem_image_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='display_name',
            field=models.CharField(blank=True, help_text="Public-facing name shown on the menu page. Leave blank to hide the category header entirely. Use for time-sensitive labels e.g. 'Week of May 25'.", max_length=100),
        ),
        migrations.AddField(
            model_name='menusubcategory',
            name='display_name',
            field=models.CharField(blank=True, help_text="Public-facing name shown on the menu page. Leave blank to hide the category header entirely. Use for time-sensitive labels e.g. 'Week of May 25'.", max_length=100),
        ),
    ]
