# Generated by Django 6.0.3 on 2026-05-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_display_name_category_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='valid_from',
            field=models.DateField(blank=True, help_text='First day this specials menu is valid. Leave blank for non-specials menus.', null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Last day this specials menu is valid. Menu auto-hides after this date.', null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_type',
            field=models.CharField(choices=[('food', 'Food'), ('drinks', 'Drinks'), ('promo', 'Promotion'), ('weekly_specials', 'Weekly Specials')], default='promo', help_text='Food or Drinks for role-assigned menus. Promotion enables color scheme and homepage display.', max_length=20),
        ),
    ]
