# Generated by Django 6.0.3 on 2026-05-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_weekly_specials_menu_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='display_name',
            field=models.CharField(blank=True, help_text="Public-facing name shown on the menu page and nav. Leave blank to use the internal name field. Use for seasonal or time-sensitive labels e.g. 'Summer Cocktails' or 'Week of May 25 Specials'.", max_length=200),
        ),
    ]
