# Generated by Django 6.0.3 on 2026-04-07 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_contentblock_active_from_contentblock_active_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Machine name used to look up this group in templates and views', max_length=100, unique=True)),
                ('label', models.CharField(help_text='Human-readable name shown in admin', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional hint for editors about where/how this group is used')),
            ],
            options={
                'verbose_name': 'Content Group',
                'verbose_name_plural': 'Content Groups',
                'ordering': ['slug'],
            },
        ),
        migrations.AddField(
            model_name='contentblock',
            name='button_label',
            field=models.CharField(blank=True, help_text="Button text, e.g. 'Reserve a Table'. Only used when slot component_type is Button.", max_length=100),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='button_url',
            field=models.URLField(blank=True, help_text='Button destination URL. Only used when slot component_type is Button.'),
        ),
        migrations.AddField(
            model_name='contentslot',
            name='component_type',
            field=models.CharField(blank=True, choices=[('title', 'Title'), ('subtitle', 'Subtitle / Tagline'), ('body', 'Body / Description'), ('footer', 'Footer / CTA Text'), ('image', 'Image'), ('button', 'Button')], default='', help_text='Role this slot plays within its group. Leave blank for standalone slots.', max_length=20),
        ),
        migrations.AddField(
            model_name='contentslot',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Display order within the group among slots of the same component type'),
        ),
        migrations.AddField(
            model_name='contentslot',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Optional: assign to a ContentGroup to make this slot part of a structured output', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='content.contentgroup'),
        ),
    ]
