# Generated by Django 6.0.3 on 2026-04-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_contentgroup_contentblock_button_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='button_url',
            field=models.CharField(blank=True, help_text='Button destination. Accepts any link format: https://example.com, /relative/path, tel:(412) 321-7646, mailto:info@example.com. Only used when slot component_type is Button.', max_length=500),
        ),
    ]
