# Generated by Django 5.0.14 on 2026-02-17 02:06

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('page_type', models.CharField(choices=[('home', 'Home Page'), ('menu', 'Menu Page'), ('events', 'Events Page'), ('about', 'About Page'), ('contact', 'Contact Page'), ('gallery', 'Gallery Page')], max_length=20)),
                ('template_file', models.CharField(help_text="Template file path relative to theme directory (e.g., 'pages/home_template1.html')", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='template_previews/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Template',
                'verbose_name_plural': 'Page Templates',
                'ordering': ['page_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('theme_directory', models.CharField(help_text="Directory name in themes/ folder (e.g., 'classic', 'modern')", max_length=100)),
                ('preview_image', models.ImageField(blank=True, help_text='Screenshot or preview of the theme', null=True, upload_to='theme_previews/')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(default='Your Restaurant', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='USA', max_length=100)),
                ('hours_text', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Restaurant hours (use rich text for formatting)')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for search engines (max 160 characters)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('maintenance_mode', models.BooleanField(default=False, help_text="Enable maintenance mode to show 'Coming Soon' page")),
                ('maintenance_message', models.TextField(blank=True, help_text='Message to display during maintenance')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('events_template', models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'page_type': 'events'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_pages', to='core.pagetemplate')),
                ('home_template', models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'page_type': 'home'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_pages', to='core.pagetemplate')),
                ('menu_template', models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'page_type': 'menu'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_pages', to='core.pagetemplate')),
                ('active_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_settings', to='core.theme')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
