# Generated by Django 5.0.14 on 2026-02-20 15:24

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('page_type', models.CharField(choices=[('home', 'Home Page'), ('menu', 'Menu Page'), ('promotions', 'Promotions Page'), ('about', 'About Page'), ('contact', 'Contact Page'), ('gallery', 'Gallery Page')], max_length=20)),
                ('template_file', models.CharField(help_text="Template file path relative to theme directory (e.g., 'pages/home_template1.html')", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='template_previews/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Template',
                'verbose_name_plural': 'Page Templates',
                'ordering': ['page_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('theme_directory', models.CharField(help_text="Directory name in themes/ folder (e.g., 'classic', 'modern', 'elegant')", max_length=100)),
                ('preview_image', models.ImageField(blank=True, help_text='Screenshot or preview of this theme', null=True, upload_to='theme_previews/')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ThemeOverlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('valid_from', models.DateField(blank=True, help_text='Date this overlay becomes active (leave blank for manual control)', null=True)),
                ('valid_to', models.DateField(blank=True, help_text='Date this overlay expires (leave blank for manual control)', null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Manually force this overlay on/off (date range takes priority if set)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Theme Overlay',
                'verbose_name_plural': 'Theme Overlays',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ThemeStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('primary_font', models.CharField(blank=True, choices=[('Georgia, serif', 'Georgia'), ('"Playfair Display", serif', 'Playfair Display'), ('"Cormorant Garamond", serif', 'Cormorant Garamond'), ('"Libre Baskerville", serif', 'Libre Baskerville'), ('"Inter", sans-serif', 'Inter'), ('"Lato", sans-serif', 'Lato'), ('"Montserrat", sans-serif', 'Montserrat'), ('"Open Sans", sans-serif', 'Open Sans'), ('"Cinzel", serif', 'Cinzel (Elegant)'), ('"Oswald", sans-serif', 'Oswald'), ('"Raleway", sans-serif', 'Raleway'), ('"Courier New", monospace', 'Courier New')], help_text='Main font for headings and titles', max_length=100)),
                ('secondary_font', models.CharField(blank=True, choices=[('Georgia, serif', 'Georgia'), ('"Playfair Display", serif', 'Playfair Display'), ('"Cormorant Garamond", serif', 'Cormorant Garamond'), ('"Libre Baskerville", serif', 'Libre Baskerville'), ('"Inter", sans-serif', 'Inter'), ('"Lato", sans-serif', 'Lato'), ('"Montserrat", sans-serif', 'Montserrat'), ('"Open Sans", sans-serif', 'Open Sans'), ('"Cinzel", serif', 'Cinzel (Elegant)'), ('"Oswald", sans-serif', 'Oswald'), ('"Raleway", sans-serif', 'Raleway'), ('"Courier New", monospace', 'Courier New')], help_text='Font for body text and descriptions', max_length=100)),
                ('accent_font', models.CharField(blank=True, choices=[('Georgia, serif', 'Georgia'), ('"Playfair Display", serif', 'Playfair Display'), ('"Cormorant Garamond", serif', 'Cormorant Garamond'), ('"Libre Baskerville", serif', 'Libre Baskerville'), ('"Inter", sans-serif', 'Inter'), ('"Lato", sans-serif', 'Lato'), ('"Montserrat", sans-serif', 'Montserrat'), ('"Open Sans", sans-serif', 'Open Sans'), ('"Cinzel", serif', 'Cinzel (Elegant)'), ('"Oswald", sans-serif', 'Oswald'), ('"Raleway", sans-serif', 'Raleway'), ('"Courier New", monospace', 'Courier New')], help_text='Font for prices, labels, and accents', max_length=100)),
                ('primary_text_color', models.CharField(blank=True, help_text='Main text color (e.g., #f5f0e8)', max_length=20)),
                ('secondary_text_color', models.CharField(blank=True, help_text='Secondary/muted text color', max_length=20)),
                ('accent_text_color', models.CharField(blank=True, help_text='Accent color for prices, highlights (e.g., #c9972a)', max_length=20)),
                ('heading_text_color', models.CharField(blank=True, help_text='Color specifically for headings', max_length=20)),
                ('primary_bg_color', models.CharField(blank=True, help_text='Main page background color (e.g., #0a0a0a)', max_length=20)),
                ('secondary_bg_color', models.CharField(blank=True, help_text='Card/section background color (e.g., #1a1a1a)', max_length=20)),
                ('accent_bg_color', models.CharField(blank=True, help_text='Accent background — buttons, badges, highlights (e.g., #c9972a)', max_length=20)),
                ('nav_bg_color', models.CharField(blank=True, help_text='Navigation bar background color', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Theme Style',
                'verbose_name_plural': 'Theme Styles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(default='Your Restaurant', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='USA', max_length=100)),
                ('hours_text', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Restaurant hours (use rich text for formatting)')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('yelp_url', models.URLField(blank=True)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for search engines (max 160 characters)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('maintenance_mode', models.BooleanField(default=False, help_text="Enable maintenance mode to show 'Coming Soon' page")),
                ('maintenance_message', models.TextField(blank=True, help_text='Message to display during maintenance')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home_template', models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'page_type': 'home'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_pages', to='core.pagetemplate')),
                ('menu_template', models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'page_type': 'menu'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_pages', to='core.pagetemplate')),
                ('promotions_template', models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'page_type': 'promotions'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_pages', to='core.pagetemplate')),
                ('active_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_settings', to='core.theme')),
                ('active_overlay', models.ForeignKey(blank=True, help_text='Optional seasonal/promotion overlay applied on top of the active theme', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_settings', to='core.themeoverlay')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AddField(
            model_name='themeoverlay',
            name='style',
            field=models.ForeignKey(help_text='The style definition for this overlay', on_delete=django.db.models.deletion.PROTECT, to='core.themestyle'),
        ),
        migrations.AddField(
            model_name='theme',
            name='base_style',
            field=models.ForeignKey(blank=True, help_text='The base branding style (fonts, colors) for this theme', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_themes', to='core.themestyle'),
        ),
    ]
