# Generated by Django 5.0.14 on 2026-02-19 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeOverlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('valid_from', models.DateField(blank=True, help_text='Date this overlay becomes active (leave blank for manual control)', null=True)),
                ('valid_to', models.DateField(blank=True, help_text='Date this overlay expires (leave blank for manual control)', null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Manually force this overlay on/off (date range takes priority if set)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Theme Overlay',
                'verbose_name_plural': 'Theme Overlays',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ThemeStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('primary_font', models.CharField(blank=True, choices=[('Georgia, serif', 'Georgia'), ('"Playfair Display", serif', 'Playfair Display'), ('"Cormorant Garamond", serif', 'Cormorant Garamond'), ('"Libre Baskerville", serif', 'Libre Baskerville'), ('"Inter", sans-serif', 'Inter'), ('"Lato", sans-serif', 'Lato'), ('"Montserrat", sans-serif', 'Montserrat'), ('"Open Sans", sans-serif', 'Open Sans'), ('"Cinzel", serif', 'Cinzel (Elegant)'), ('"Oswald", sans-serif', 'Oswald'), ('"Raleway", sans-serif', 'Raleway'), ('"Courier New", monospace', 'Courier New')], help_text='Main font for headings and titles', max_length=100)),
                ('secondary_font', models.CharField(blank=True, choices=[('Georgia, serif', 'Georgia'), ('"Playfair Display", serif', 'Playfair Display'), ('"Cormorant Garamond", serif', 'Cormorant Garamond'), ('"Libre Baskerville", serif', 'Libre Baskerville'), ('"Inter", sans-serif', 'Inter'), ('"Lato", sans-serif', 'Lato'), ('"Montserrat", sans-serif', 'Montserrat'), ('"Open Sans", sans-serif', 'Open Sans'), ('"Cinzel", serif', 'Cinzel (Elegant)'), ('"Oswald", sans-serif', 'Oswald'), ('"Raleway", sans-serif', 'Raleway'), ('"Courier New", monospace', 'Courier New')], help_text='Font for body text and descriptions', max_length=100)),
                ('accent_font', models.CharField(blank=True, choices=[('Georgia, serif', 'Georgia'), ('"Playfair Display", serif', 'Playfair Display'), ('"Cormorant Garamond", serif', 'Cormorant Garamond'), ('"Libre Baskerville", serif', 'Libre Baskerville'), ('"Inter", sans-serif', 'Inter'), ('"Lato", sans-serif', 'Lato'), ('"Montserrat", sans-serif', 'Montserrat'), ('"Open Sans", sans-serif', 'Open Sans'), ('"Cinzel", serif', 'Cinzel (Elegant)'), ('"Oswald", sans-serif', 'Oswald'), ('"Raleway", sans-serif', 'Raleway'), ('"Courier New", monospace', 'Courier New')], help_text='Font for prices, labels, and accents', max_length=100)),
                ('primary_text_color', models.CharField(blank=True, help_text='Main text color (e.g., #1a1a1a)', max_length=20)),
                ('secondary_text_color', models.CharField(blank=True, help_text='Secondary/muted text color', max_length=20)),
                ('accent_text_color', models.CharField(blank=True, help_text='Accent color for prices, highlights', max_length=20)),
                ('heading_text_color', models.CharField(blank=True, help_text='Color specifically for headings', max_length=20)),
                ('primary_bg_color', models.CharField(blank=True, help_text='Main page background color', max_length=20)),
                ('secondary_bg_color', models.CharField(blank=True, help_text='Card/section background color', max_length=20)),
                ('accent_bg_color', models.CharField(blank=True, help_text='Accent background (buttons, badges, highlights)', max_length=20)),
                ('nav_bg_color', models.CharField(blank=True, help_text='Navigation bar background color', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Theme Style',
                'verbose_name_plural': 'Theme Styles',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='events_template',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promotions_template',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'page_type': 'promotions'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_pages', to='core.pagetemplate'),
        ),
        migrations.AlterField(
            model_name='pagetemplate',
            name='page_type',
            field=models.CharField(choices=[('home', 'Home Page'), ('menu', 'Menu Page'), ('promotions', 'Promotions Page'), ('about', 'About Page'), ('contact', 'Contact Page'), ('gallery', 'Gallery Page')], max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='active_overlay',
            field=models.ForeignKey(blank=True, help_text='Optional seasonal/promotion overlay applied on top of the active theme', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_settings', to='core.themeoverlay'),
        ),
        migrations.AddField(
            model_name='themeoverlay',
            name='style',
            field=models.ForeignKey(help_text='The style definition for this overlay', on_delete=django.db.models.deletion.PROTECT, to='core.themestyle'),
        ),
        migrations.AddField(
            model_name='theme',
            name='base_style',
            field=models.ForeignKey(blank=True, help_text='The base branding style (fonts, colors) for this theme', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_themes', to='core.themestyle'),
        ),
    ]
