# Generated by Django 5.0.14 on 2026-02-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='yelp_url',
        ),
    ]
