# Generated by Django 5.0.14 on 2026-02-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_sitesettings_yelp_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='yelp_url',
            field=models.URLField(blank=True),
        ),
    ]
