# Generated by Django 5.0.14 on 2026-03-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_yelp_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='themestyle',
            name='dark_gray_color',
            field=models.CharField(blank=True, help_text='--color-dark-gray — borders and dividers (e.g. #2c2c2c)', max_length=30),
        ),
        migrations.AddField(
            model_name='themestyle',
            name='gold_bright_color',
            field=models.CharField(blank=True, help_text='--color-gold-bright — hover states and highlights (e.g. #e8b84b)', max_length=30),
        ),
        migrations.AddField(
            model_name='themestyle',
            name='gold_deep_color',
            field=models.CharField(blank=True, help_text='--color-gold-deep — borders, subtle dividers (e.g. #a07820)', max_length=30),
        ),
        migrations.AddField(
            model_name='themestyle',
            name='gold_light_color',
            field=models.CharField(blank=True, help_text='--color-gold-light — tints and washes (e.g. #f4d98a)', max_length=30),
        ),
        migrations.AddField(
            model_name='themestyle',
            name='gold_primary_color',
            field=models.CharField(blank=True, help_text='--color-gold-primary — official brand gold (e.g. #ffb612 for Steelers overlay)', max_length=30),
        ),
        migrations.AddField(
            model_name='themestyle',
            name='mid_gray_color',
            field=models.CharField(blank=True, help_text='--color-mid-gray — placeholder text (e.g. #555555)', max_length=30),
        ),
        migrations.AddField(
            model_name='themestyle',
            name='nav_text_color',
            field=models.CharField(blank=True, help_text='--color-text-nav — navigation link color (stays light regardless of theme)', max_length=30),
        ),
        migrations.AddField(
            model_name='themestyle',
            name='tertiary_bg_color',
            field=models.CharField(blank=True, help_text='--color-bg-tertiary — third-level surface, e.g. deep red accent area', max_length=30),
        ),
        migrations.AddField(
            model_name='themestyle',
            name='tertiary_text_color',
            field=models.CharField(blank=True, help_text='--color-text-tertiary — third-level text, captions (e.g. #eccb9c)', max_length=30),
        ),
        migrations.AlterField(
            model_name='themestyle',
            name='accent_bg_color',
            field=models.CharField(blank=True, help_text='--color-bg-accent — CTA buttons, badges, highlights (e.g. #c9972a)', max_length=30),
        ),
        migrations.AlterField(
            model_name='themestyle',
            name='accent_font',
            field=models.CharField(blank=True, choices=[('Georgia, serif', 'Georgia'), ('"Playfair Display", serif', 'Playfair Display'), ('"Cormorant Garamond", serif', 'Cormorant Garamond'), ('"Libre Baskerville", serif', 'Libre Baskerville'), ('"Inter", sans-serif', 'Inter'), ('"Lato", sans-serif', 'Lato'), ('"Montserrat", sans-serif', 'Montserrat'), ('"Open Sans", sans-serif', 'Open Sans'), ('"Cinzel", serif', 'Cinzel (Elegant)'), ('"Oswald", sans-serif', 'Oswald'), ('"Raleway", sans-serif', 'Raleway'), ('"Courier New", monospace', 'Courier New')], help_text='--font-accent — prices, labels, and UI accents', max_length=100),
        ),
        migrations.AlterField(
            model_name='themestyle',
            name='accent_text_color',
            field=models.CharField(blank=True, help_text='--color-text-accent — gold highlights, prices, links (e.g. #c9972a)', max_length=30),
        ),
        migrations.AlterField(
            model_name='themestyle',
            name='heading_text_color',
            field=models.CharField(blank=True, help_text='--color-text-heading — h1–h6 color', max_length=30),
        ),
        migrations.AlterField(
            model_name='themestyle',
            name='nav_bg_color',
            field=models.CharField(blank=True, help_text='--color-nav-bg — sticky navigation bar background', max_length=30),
        ),
        migrations.AlterField(
            model_name='themestyle',
            name='primary_bg_color',
            field=models.CharField(blank=True, help_text='--color-bg-primary — main page background (e.g. #0a0a0a)', max_length=30),
        ),
        migrations.AlterField(
            model_name='themestyle',
            name='primary_font',
            field=models.CharField(blank=True, choices=[('Georgia, serif', 'Georgia'), ('"Playfair Display", serif', 'Playfair Display'), ('"Cormorant Garamond", serif', 'Cormorant Garamond'), ('"Libre Baskerville", serif', 'Libre Baskerville'), ('"Inter", sans-serif', 'Inter'), ('"Lato", sans-serif', 'Lato'), ('"Montserrat", sans-serif', 'Montserrat'), ('"Open Sans", sans-serif', 'Open Sans'), ('"Cinzel", serif', 'Cinzel (Elegant)'), ('"Oswald", sans-serif', 'Oswald'), ('"Raleway", sans-serif', 'Raleway'), ('"Courier New", monospace', 'Courier New')], help_text='--font-primary — headings and titles', max_length=100),
        ),
        migrations.AlterField(
            model_name='themestyle',
            name='primary_text_color',
            field=models.CharField(blank=True, help_text='--color-text-primary — main body text (e.g. #f5f0e8)', max_length=30),
        ),
        migrations.AlterField(
            model_name='themestyle',
            name='secondary_bg_color',
            field=models.CharField(blank=True, help_text='--color-bg-secondary — cards, panels, surfaces (e.g. #1a1a1a)', max_length=30),
        ),
        migrations.AlterField(
            model_name='themestyle',
            name='secondary_font',
            field=models.CharField(blank=True, choices=[('Georgia, serif', 'Georgia'), ('"Playfair Display", serif', 'Playfair Display'), ('"Cormorant Garamond", serif', 'Cormorant Garamond'), ('"Libre Baskerville", serif', 'Libre Baskerville'), ('"Inter", sans-serif', 'Inter'), ('"Lato", sans-serif', 'Lato'), ('"Montserrat", sans-serif', 'Montserrat'), ('"Open Sans", sans-serif', 'Open Sans'), ('"Cinzel", serif', 'Cinzel (Elegant)'), ('"Oswald", sans-serif', 'Oswald'), ('"Raleway", sans-serif', 'Raleway'), ('"Courier New", monospace', 'Courier New')], help_text='--font-secondary — body text and descriptions', max_length=100),
        ),
        migrations.AlterField(
            model_name='themestyle',
            name='secondary_text_color',
            field=models.CharField(blank=True, help_text='--color-text-secondary — muted/supporting text', max_length=30),
        ),
    ]
