# Generated by Django 5.0.14 on 2026-03-06 16:27

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_themestyle_dark_gray_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='catering_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Statement about catering (use rich text for formatting)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='short_about_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Short about section for home page (use rich text for formatting)'),
        ),
    ]
