# Generated by Django 5.0.14 on 2026-03-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_catering_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themestyle',
            name='accent_bg_color',
        ),
        migrations.RemoveField(
            model_name='themestyle',
            name='accent_text_color',
        ),
        migrations.RemoveField(
            model_name='themestyle',
            name='dark_gray_color',
        ),
        migrations.RemoveField(
            model_name='themestyle',
            name='gold_bright_color',
        ),
        migrations.RemoveField(
            model_name='themestyle',
            name='gold_deep_color',
        ),
        migrations.RemoveField(
            model_name='themestyle',
            name='gold_light_color',
        ),
        migrations.RemoveField(
            model_name='themestyle',
            name='gold_primary_color',
        ),
        migrations.RemoveField(
            model_name='themestyle',
            name='heading_text_color',
        ),
        migrations.RemoveField(
            model_name='themestyle',
            name='mid_gray_color',
        ),
        migrations.RemoveField(
            model_name='themestyle',
            name='nav_bg_color',
        ),
        migrations.RemoveField(
            model_name='themestyle',
            name='nav_text_color',
        ),
        migrations.RemoveField(
            model_name='themestyle',
            name='primary_bg_color',
        ),
        migrations.RemoveField(
            model_name='themestyle',
            name='primary_text_color',
        ),
        migrations.RemoveField(
            model_name='themestyle',
            name='secondary_bg_color',
        ),
        migrations.RemoveField(
            model_name='themestyle',
            name='secondary_text_color',
        ),
        migrations.RemoveField(
            model_name='themestyle',
            name='tertiary_bg_color',
        ),
        migrations.RemoveField(
            model_name='themestyle',
            name='tertiary_text_color',
        ),
        migrations.AddField(
            model_name='themestyle',
            name='promo_accent_color',
            field=models.CharField(blank=True, help_text='--color-promo-accent — secondary promo color (e.g. #006600 for Christmas)', max_length=30),
        ),
        migrations.AddField(
            model_name='themestyle',
            name='promo_bg_color',
            field=models.CharField(blank=True, help_text='--color-promo-bg — background color for promo components', max_length=30),
        ),
        migrations.AddField(
            model_name='themestyle',
            name='promo_primary_color',
            field=models.CharField(blank=True, help_text='--color-promo-primary — main promo color (e.g. #cc0000 for Christmas)', max_length=30),
        ),
        migrations.AddField(
            model_name='themestyle',
            name='promo_text_color',
            field=models.CharField(blank=True, help_text='--color-promo-text — text color within promo components', max_length=30),
        ),
    ]
