# Generated by Django 5.0.14 on 2026-03-06 19:15

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_themestyle_accent_bg_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themestyle',
            name='promo_accent_color',
        ),
        migrations.RemoveField(
            model_name='themestyle',
            name='promo_bg_color',
        ),
        migrations.RemoveField(
            model_name='themestyle',
            name='promo_primary_color',
        ),
        migrations.RemoveField(
            model_name='themestyle',
            name='promo_text_color',
        ),
        migrations.AlterField(
            model_name='pagetemplate',
            name='template_file',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='active_overlay',
            field=models.ForeignKey(blank=True, help_text='Optional seasonal font overlay applied on top of the active theme', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_settings', to='core.themeoverlay'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='catering_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hours_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='maintenance_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description',
            field=models.TextField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='short_about_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='base_style',
            field=models.ForeignKey(blank=True, help_text='Base font style for this theme', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='themes', to='core.themestyle'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='theme_previews/'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='theme_directory',
            field=models.CharField(help_text="Folder name under templates/themes/ (e.g., 'classic', 'elegant')", max_length=100),
        ),
        migrations.AlterField(
            model_name='themeoverlay',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Manual activation toggle — used when no date range is set'),
        ),
        migrations.AlterField(
            model_name='themeoverlay',
            name='style',
            field=models.ForeignKey(help_text='Font style to apply when this overlay is active', on_delete=django.db.models.deletion.PROTECT, related_name='overlays', to='core.themestyle'),
        ),
        migrations.AlterField(
            model_name='themeoverlay',
            name='valid_from',
            field=models.DateField(blank=True, help_text='Start date for automatic activation (leave blank for manual control)', null=True),
        ),
        migrations.AlterField(
            model_name='themeoverlay',
            name='valid_to',
            field=models.DateField(blank=True, help_text='End date for automatic activation (leave blank for manual control)', null=True),
        ),
    ]
