# Generated by Django 5.0.14 on 2026-03-08 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_content_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='promotions_template',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='menu_template',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='home_template',
        ),
        migrations.DeleteModel(
            name='PageTemplate',
        ),
    ]
