# Generated by Django 5.0.14 on 2026-03-24 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_sitesettings_promotions_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='active_overlay',
        ),
        migrations.DeleteModel(
            name='ThemeOverlay',
        ),
    ]
