# Generated by Django 5.0.14 on 2026-03-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_sitesettings_active_overlay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='base_style',
        ),
        migrations.AddField(
            model_name='theme',
            name='accent_font',
            field=models.CharField(blank=True, choices=[('Georgia, serif', 'Georgia'), ('"Playfair Display", serif', 'Playfair Display'), ('"Cormorant Garamond", serif', 'Cormorant Garamond'), ('"Libre Baskerville", serif', 'Libre Baskerville'), ('"Inter", sans-serif', 'Inter'), ('"Lato", sans-serif', 'Lato'), ('"Montserrat", sans-serif', 'Montserrat'), ('"Open Sans", sans-serif', 'Open Sans'), ('"Cinzel", serif', 'Cinzel (Elegant)'), ('"Oswald", sans-serif', 'Oswald'), ('"Raleway", sans-serif', 'Raleway'), ('"Courier New", monospace', 'Courier New')], help_text='--font-accent — prices, labels, and UI accents', max_length=100),
        ),
        migrations.AddField(
            model_name='theme',
            name='primary_font',
            field=models.CharField(blank=True, choices=[('Georgia, serif', 'Georgia'), ('"Playfair Display", serif', 'Playfair Display'), ('"Cormorant Garamond", serif', 'Cormorant Garamond'), ('"Libre Baskerville", serif', 'Libre Baskerville'), ('"Inter", sans-serif', 'Inter'), ('"Lato", sans-serif', 'Lato'), ('"Montserrat", sans-serif', 'Montserrat'), ('"Open Sans", sans-serif', 'Open Sans'), ('"Cinzel", serif', 'Cinzel (Elegant)'), ('"Oswald", sans-serif', 'Oswald'), ('"Raleway", sans-serif', 'Raleway'), ('"Courier New", monospace', 'Courier New')], help_text='--font-primary — headings and titles', max_length=100),
        ),
        migrations.AddField(
            model_name='theme',
            name='secondary_font',
            field=models.CharField(blank=True, choices=[('Georgia, serif', 'Georgia'), ('"Playfair Display", serif', 'Playfair Display'), ('"Cormorant Garamond", serif', 'Cormorant Garamond'), ('"Libre Baskerville", serif', 'Libre Baskerville'), ('"Inter", sans-serif', 'Inter'), ('"Lato", sans-serif', 'Lato'), ('"Montserrat", sans-serif', 'Montserrat'), ('"Open Sans", sans-serif', 'Open Sans'), ('"Cinzel", serif', 'Cinzel (Elegant)'), ('"Oswald", sans-serif', 'Oswald'), ('"Raleway", sans-serif', 'Raleway'), ('"Courier New", monospace', 'Courier New')], help_text='--font-secondary — body text and descriptions', max_length=100),
        ),
        migrations.DeleteModel(
            name='ThemeStyle',
        ),
    ]
