# Generated by Django 5.0.14 on 2026-03-26 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_theme_base_style_theme_accent_font_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='active_theme',
            field=models.ForeignKey(blank=True, help_text='The theme currently in use. Only active themes can be selected.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_settings', to='core.theme'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='is_active',
            field=models.BooleanField(default=False, help_text="Enable this theme so it can be selected as the site's active theme."),
        ),
    ]
