# Generated by Django 6.0.3 on 2026-03-30 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_sitesettings_active_theme_and_more'),
        ('media_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='accent_font',
            field=models.CharField(blank=True, choices=[('Georgia, serif', 'Georgia'), ('"Playfair Display", serif', 'Playfair Display'), ('"Cormorant Garamond", serif', 'Cormorant Garamond'), ('"Libre Baskerville", serif', 'Libre Baskerville'), ('"Inter", sans-serif', 'Inter'), ('"Lato", sans-serif', 'Lato'), ('"Montserrat", sans-serif', 'Montserrat'), ('"Open Sans", sans-serif', 'Open Sans'), ('"Cinzel", serif', 'Cinzel (Elegant)'), ('"Oswald", sans-serif', 'Oswald'), ('"Raleway", sans-serif', 'Raleway'), ('"Courier New", monospace', 'Courier New'), ('"Playwrite IE", sans-serif', 'Playwrite IE')], help_text='--font-accent — prices, labels, and UI accents', max_length=100),
        ),
        migrations.AlterField(
            model_name='theme',
            name='primary_font',
            field=models.CharField(blank=True, choices=[('Georgia, serif', 'Georgia'), ('"Playfair Display", serif', 'Playfair Display'), ('"Cormorant Garamond", serif', 'Cormorant Garamond'), ('"Libre Baskerville", serif', 'Libre Baskerville'), ('"Inter", sans-serif', 'Inter'), ('"Lato", sans-serif', 'Lato'), ('"Montserrat", sans-serif', 'Montserrat'), ('"Open Sans", sans-serif', 'Open Sans'), ('"Cinzel", serif', 'Cinzel (Elegant)'), ('"Oswald", sans-serif', 'Oswald'), ('"Raleway", sans-serif', 'Raleway'), ('"Courier New", monospace', 'Courier New'), ('"Playwrite IE", sans-serif', 'Playwrite IE')], help_text='--font-primary — headings and titles', max_length=100),
        ),
        migrations.AlterField(
            model_name='theme',
            name='secondary_font',
            field=models.CharField(blank=True, choices=[('Georgia, serif', 'Georgia'), ('"Playfair Display", serif', 'Playfair Display'), ('"Cormorant Garamond", serif', 'Cormorant Garamond'), ('"Libre Baskerville", serif', 'Libre Baskerville'), ('"Inter", sans-serif', 'Inter'), ('"Lato", sans-serif', 'Lato'), ('"Montserrat", sans-serif', 'Montserrat'), ('"Open Sans", sans-serif', 'Open Sans'), ('"Cinzel", serif', 'Cinzel (Elegant)'), ('"Oswald", sans-serif', 'Oswald'), ('"Raleway", sans-serif', 'Raleway'), ('"Courier New", monospace', 'Courier New'), ('"Playwrite IE", sans-serif', 'Playwrite IE')], help_text='--font-secondary — body text and descriptions', max_length=100),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Referenced in the view, e.g. 'hero', 'grubhub'. Never change after deploy.", max_length=100, unique=True)),
                ('label', models.CharField(help_text="Admin-only label, e.g. 'Home Hero Banner'", max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True, help_text='Boilerplate body copy shown when no seasonal ContentBlock is active.')),
                ('bg_color', models.CharField(choices=[('bg-primary', 'Primary Background'), ('bg-secondary', 'Secondary Background'), ('steeler-black', 'Steeler Black'), ('steeler-gold', 'Steeler Gold'), ('text-primary', 'Primary Text'), ('text-secondary', 'Secondary Text'), ('gold-bright', 'Gold Bright')], default='bg-primary', max_length=50)),
                ('text_color', models.CharField(choices=[('bg-primary', 'Primary Background'), ('bg-secondary', 'Secondary Background'), ('steeler-black', 'Steeler Black'), ('steeler-gold', 'Steeler Gold'), ('text-primary', 'Primary Text'), ('text-secondary', 'Secondary Text'), ('gold-bright', 'Gold Bright')], default='text-primary', max_length=50)),
                ('image_opacity', models.DecimalField(decimal_places=2, default=0.4, help_text='0.00 = invisible, 1.00 = full opacity.', max_digits=3)),
                ('image_only', models.BooleanField(default=False, help_text='When checked, all text and buttons are hidden — image background only.')),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ForeignKey(blank=True, help_text='Background image pulled from the media manager.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='media_manager.media')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='BannerButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('href', models.CharField(max_length=500)),
                ('bg_color', models.CharField(choices=[('bg-primary', 'Primary Background'), ('bg-secondary', 'Secondary Background'), ('steeler-black', 'Steeler Black'), ('steeler-gold', 'Steeler Gold'), ('text-primary', 'Primary Text'), ('text-secondary', 'Secondary Text'), ('gold-bright', 'Gold Bright')], default='bg-secondary', max_length=50)),
                ('text_color', models.CharField(choices=[('bg-primary', 'Primary Background'), ('bg-secondary', 'Secondary Background'), ('steeler-black', 'Steeler Black'), ('steeler-gold', 'Steeler Gold'), ('text-primary', 'Primary Text'), ('text-secondary', 'Secondary Text'), ('gold-bright', 'Gold Bright')], default='text-primary', max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='core.banner')),
            ],
            options={
                'verbose_name': 'Button',
                'verbose_name_plural': 'Buttons',
                'ordering': ['order'],
            },
        ),
    ]
