# Generated by Django 6.0.3 on 2026-03-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_banner_bg_color_alter_banner_text_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='bg_color',
            field=models.CharField(choices=[('bg-primary', 'Primary Background'), ('bg-secondary', 'Secondary Background'), ('bg-tertiary', 'Tertiary Background'), ('white', 'White'), ('steeler-black', 'Steeler Black'), ('steeler-gold', 'Steeler Gold'), ('text-primary', 'Primary Text'), ('text-secondary', 'Secondary Text'), ('text-tertiary', 'Tertiary Text'), ('gold-bright', 'Gold Bright')], default='bg-primary', max_length=50),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_color',
            field=models.CharField(choices=[('bg-primary', 'Primary Background'), ('bg-secondary', 'Secondary Background'), ('bg-tertiary', 'Tertiary Background'), ('white', 'White'), ('steeler-black', 'Steeler Black'), ('steeler-gold', 'Steeler Gold'), ('text-primary', 'Primary Text'), ('text-secondary', 'Secondary Text'), ('text-tertiary', 'Tertiary Text'), ('gold-bright', 'Gold Bright')], default='text-primary', max_length=50),
        ),
        migrations.AlterField(
            model_name='bannerbutton',
            name='bg_color',
            field=models.CharField(choices=[('bg-primary', 'Primary Background'), ('bg-secondary', 'Secondary Background'), ('bg-tertiary', 'Tertiary Background'), ('white', 'White'), ('steeler-black', 'Steeler Black'), ('steeler-gold', 'Steeler Gold'), ('text-primary', 'Primary Text'), ('text-secondary', 'Secondary Text'), ('text-tertiary', 'Tertiary Text'), ('gold-bright', 'Gold Bright')], default='bg-secondary', max_length=50),
        ),
        migrations.AlterField(
            model_name='bannerbutton',
            name='text_color',
            field=models.CharField(choices=[('bg-primary', 'Primary Background'), ('bg-secondary', 'Secondary Background'), ('bg-tertiary', 'Tertiary Background'), ('white', 'White'), ('steeler-black', 'Steeler Black'), ('steeler-gold', 'Steeler Gold'), ('text-primary', 'Primary Text'), ('text-secondary', 'Secondary Text'), ('text-tertiary', 'Tertiary Text'), ('gold-bright', 'Gold Bright')], default='text-primary', max_length=50),
        ),
    ]
