# Generated by Django 6.0.3 on 2026-03-30 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('core', '0016_alter_banner_bg_color_alter_banner_text_color_and_more'),
        ('media_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Referenced in the view, e.g. 'front-door-image', 'about-text'. Never change after deploy.", max_length=100, unique=True)),
                ('label', models.CharField(help_text="Admin-only label, e.g. 'Front Door Image Panel'", max_length=200)),
                ('mode', models.CharField(choices=[('text', 'Text & Button'), ('image', 'Full Image')], default='text', help_text='Image: full-bleed photo. Text: title, copy, and optional button.', max_length=10)),
                ('bg_color', models.CharField(choices=[('bg-primary', 'Primary Background'), ('bg-secondary', 'Secondary Background'), ('bg-tertiary', 'Tertiary Background'), ('white', 'White'), ('steeler-black', 'Steeler Black'), ('steeler-gold', 'Steeler Gold'), ('text-primary', 'Primary Text'), ('text-secondary', 'Secondary Text'), ('text-tertiary', 'Tertiary Text'), ('gold-bright', 'Gold Bright')], default='bg-primary', help_text='Background color. For image panels, shows while image loads.', max_length=50)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('text_color', models.CharField(choices=[('bg-primary', 'Primary Background'), ('bg-secondary', 'Secondary Background'), ('bg-tertiary', 'Tertiary Background'), ('white', 'White'), ('steeler-black', 'Steeler Black'), ('steeler-gold', 'Steeler Gold'), ('text-primary', 'Primary Text'), ('text-secondary', 'Secondary Text'), ('text-tertiary', 'Tertiary Text'), ('gold-bright', 'Gold Bright')], default='text-primary', max_length=50)),
                ('button_label', models.CharField(blank=True, max_length=100)),
                ('button_href', models.CharField(blank=True, max_length=500)),
                ('button_bg_color', models.CharField(blank=True, choices=[('bg-primary', 'Primary Background'), ('bg-secondary', 'Secondary Background'), ('bg-tertiary', 'Tertiary Background'), ('white', 'White'), ('steeler-black', 'Steeler Black'), ('steeler-gold', 'Steeler Gold'), ('text-primary', 'Primary Text'), ('text-secondary', 'Secondary Text'), ('text-tertiary', 'Tertiary Text'), ('gold-bright', 'Gold Bright')], default='bg-secondary', max_length=50)),
                ('button_text_color', models.CharField(blank=True, choices=[('bg-primary', 'Primary Background'), ('bg-secondary', 'Secondary Background'), ('bg-tertiary', 'Tertiary Background'), ('white', 'White'), ('steeler-black', 'Steeler Black'), ('steeler-gold', 'Steeler Gold'), ('text-primary', 'Primary Text'), ('text-secondary', 'Secondary Text'), ('text-tertiary', 'Tertiary Text'), ('gold-bright', 'Gold Bright')], default='text-primary', max_length=50)),
                ('image_fallback_url', models.CharField(blank=True, help_text="Static fallback path if no media manager image is set, e.g. '/static/img/front_door.webp'.", max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('content_slot', models.ForeignKey(blank=True, help_text='Optional ContentSlot for body copy. Active block is resolved at render time.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_sides', to='content.contentslot')),
                ('image', models.ForeignKey(blank=True, help_text="Full-bleed image. Used when mode is 'image'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_sides', to='media_manager.media')),
            ],
            options={
                'verbose_name': 'Panel Side',
                'verbose_name_plural': 'Panel Sides',
                'ordering': ['slug'],
            },
        ),
    ]
