# Generated by Django 6.0.3 on 2026-03-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_panelside'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelside',
            name='vertical_align',
            field=models.CharField(blank=True, choices=[('start', 'Top'), ('center', 'Middle'), ('end', 'Bottom')], default='center', max_length=10),
        ),
    ]
