# Generated by Django 6.0.3 on 2026-03-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_panelside_vertical_align'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelside',
            name='horizontal_align',
            field=models.CharField(blank=True, choices=[('start', 'Left'), ('center', 'Center'), ('end', 'Right')], default='start', max_length=10),
        ),
    ]
