# Generated by Django 6.0.3 on 2026-03-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_panelside_horizontal_align'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelside',
            name='horizontal_align',
            field=models.CharField(blank=True, choices=[('flex-start', 'Left'), ('center', 'Center'), ('flex-end', 'Right')], default='start', max_length=10),
        ),
        migrations.AlterField(
            model_name='panelside',
            name='vertical_align',
            field=models.CharField(blank=True, choices=[('flex-start', 'Top'), ('center', 'Middle'), ('flex-end', 'Bottom')], default='center', max_length=10),
        ),
    ]
