# Generated by Django 6.0.3 on 2026-03-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_panelside_horizontal_align_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelside',
            name='horizontal_align',
            field=models.CharField(blank=True, choices=[('flex-start', 'Left'), ('center', 'Center'), ('flex-end', 'Right')], default='flex-start', max_length=12),
        ),
        migrations.AlterField(
            model_name='panelside',
            name='vertical_align',
            field=models.CharField(blank=True, choices=[('flex-start', 'Top'), ('center', 'Middle'), ('flex-end', 'Bottom')], default='center', max_length=12),
        ),
    ]
