# Generated by Django 6.0.3 on 2026-03-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_panelside_horizontal_align_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelside',
            name='mode',
            field=models.CharField(choices=[('text', 'Text & Button'), ('image', 'Full Image'), ('map', 'Google Maps Embed')], default='text', help_text='Image: full-bleed photo. Text: title, copy, and optional button.', max_length=10),
        ),
    ]
