# Generated by Django 6.0.3 on 2026-04-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_panelside_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='force_full_menu',
            field=models.BooleanField(default=False, help_text='Force full menu on regardless of the event calendar or game day mode. Takes precedence over force_game_day_mode. Use this to override a calendar event that was cancelled or rescheduled.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='force_game_day_mode',
            field=models.BooleanField(default=False, help_text='Force limited menu mode on regardless of the event calendar. Useful for unexpected busy periods not on the schedule. Remember to uncheck this after the situation passes.'),
        ),
    ]
