# Generated by Django 6.0.3 on 2026-04-16 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_banner_created_at_banner_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='active_theme',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
