# Generated by Django 6.0.3 on 2026-04-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_sitesettings_active_theme_delete_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='reservations_url',
            field=models.URLField(blank=True, help_text='OpenTable or other reservations link. Used for the Reservations button on the homepage.'),
        ),
    ]
