# Generated by Django 6.0.3 on 2026-05-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_reservations_url_to_site_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('preferred_contact', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default='email', max_length=10)),
                ('event_type', models.CharField(choices=[('private_party', 'Private Party'), ('corporate', 'Corporate Event'), ('birthday', 'Birthday'), ('other', 'Other')], default='private_party', max_length=20)),
                ('guest_count', models.PositiveIntegerField(blank=True, null=True)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('menu_preference', models.CharField(choices=[('full', 'Full Menu'), ('limited', 'Limited Menu'), ('not_sure', 'Not Sure / Flexible')], default='not_sure', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20)),
            ],
            options={
                'verbose_name': 'Event Inquiry',
                'verbose_name_plural': 'Event Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
