# Generated by Django 6.0.3 on 2026-05-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_eventinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='notification_email',
            field=models.EmailField(blank=True, help_text='Internal address for staff alerts (new inquiries, etc.). Falls back to the contact email above if blank.', max_length=254),
        ),
    ]
