# Generated by Django 6.0.3 on 2026-05-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_sitesettings_notification_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Internal name — not shown to visitors', max_length=100)),
                ('heading', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('cta_label', models.CharField(blank=True, max_length=100, verbose_name='Button label')),
                ('cta_url', models.URLField(blank=True, verbose_name='Button URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='popups/')),
                ('bg_color', models.CharField(default='#1a1a1a', max_length=20, verbose_name='Background colour')),
                ('text_color', models.CharField(default='#ffffff', max_length=20, verbose_name='Text colour')),
                ('accent_color', models.CharField(default='#c9972a', max_length=20, verbose_name='Accent/button colour')),
                ('show_delay', models.PositiveIntegerField(default=2, help_text='Seconds before the popup appears')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Site Popup',
                'verbose_name_plural': 'Site Popups',
                'ordering': ['-created_at'],
            },
        ),
    ]
