# Generated by Django 6.0.3 on 2026-05-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_sitepopup'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepopup',
            name='show_subscribe_form',
            field=models.BooleanField(default=False, help_text='Embed the mailing-list signup form instead of the CTA button', verbose_name='Show email signup form'),
        ),
    ]
