# Generated by Django 6.0.3 on 2026-05-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_sitepopup_subscribe_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepopup',
            name='primary_color',
            field=models.CharField(default='#c9972a', max_length=20, verbose_name='Primary/heading colour'),
        ),
    ]
