# Generated by Django 6.0.3 on 2026-05-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_move_colorscheme_from_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorscheme',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
