# Generated by Django 6.0.3 on 2026-05-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_colorscheme_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelside',
            name='image_fallback_url',
            field=models.CharField(blank=True, help_text="Static fallback path, e.g. '/static/img/front_door.webp'.", max_length=500),
        ),
    ]
