# Generated by Django 6.0.3 on 2026-05-24 20:29

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_fix_banner_panelside_image_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.models.SlugUpload('banners')),
        ),
        migrations.AlterField(
            model_name='panelside',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.models.SlugUpload('panels')),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.models.SiteUpload('favicon')),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.models.SiteUpload('logo')),
        ),
    ]
