# Generated by Django 6.0.3 on 2026-05-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_banner_image_alter_panelside_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer_name', models.CharField(max_length=100)),
                ('reviewer_location', models.CharField(blank=True, max_length=100)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('body', models.TextField()),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('google', 'Google'), ('yelp', 'Yelp'), ('opentable', 'OpenTable'), ('rewardsnetwork', 'Rewards Network')], default='google', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on the homepage sampling (up to 3 featured reviews displayed).')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_review_url',
            field=models.URLField(blank=True, help_text="Google Maps 'Write a review' link"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='opentable_review_url',
            field=models.URLField(blank=True, help_text='OpenTable reviews page link'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='rewardsnetwork_review_url',
            field=models.URLField(blank=True, help_text='Rewards Network reviews page link'),
        ),
    ]
