# Generated by Django 6.0.3 on 2026-05-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_review_sitesettings_google_review_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='yelp_review_url',
            field=models.URLField(blank=True, help_text='Yelp reviews page link'),
        ),
    ]
