# Generated by Django 6.0.3 on 2026-05-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_sitesettings_yelp_review_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, help_text="Platform's own review ID — used to skip duplicates on re-import.", max_length=200),
        ),
    ]
