# Generated by Django 6.0.3 on 2026-05-27 20:10
# Hand-edited: replaced AlterField with RemoveField+AddField pairs because
# PostgreSQL cannot ALTER a varchar/ImageField column directly to bigint (FK).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_review_source_id'),
        ('media', '0001_initial'),
    ]

    operations = [
        # Banner.image: ImageField → FK to MediaItem
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ForeignKey(
                blank=True,
                help_text='Select from the media library. Set alt text on the media item itself.',
                limit_choices_to={'owner_type': 'staff'},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='banners',
                to='media.mediaitem',
            ),
        ),

        # PanelSide.image: ImageField → FK to MediaItem
        migrations.RemoveField(
            model_name='panelside',
            name='image',
        ),
        migrations.AddField(
            model_name='panelside',
            name='image',
            field=models.ForeignKey(
                blank=True,
                help_text='Select from the media library.',
                limit_choices_to={'owner_type': 'staff'},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='panels',
                to='media.mediaitem',
            ),
        ),

        # SitePopup.image: ImageField → FK to MediaItem
        migrations.RemoveField(
            model_name='sitepopup',
            name='image',
        ),
        migrations.AddField(
            model_name='sitepopup',
            name='image',
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={'owner_type': 'staff'},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='popups',
                to='media.mediaitem',
            ),
        ),
    ]
