# Generated by Django 6.0.3 on 2026-05-27 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_banner_image_alter_panelside_image_and_more'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to temporarily hide this image without removing it.')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.banner')),
                ('media_item', models.ForeignKey(limit_choices_to={'owner_type': 'staff'}, on_delete=django.db.models.deletion.PROTECT, related_name='banner_images', to='media.mediaitem')),
            ],
            options={
                'verbose_name': 'Banner Image',
                'verbose_name_plural': 'Banner Images',
                'ordering': ['display_order'],
                'unique_together': {('banner', 'media_item')},
            },
        ),
    ]
