# Generated by Django 6.0.3 on 2026-05-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_banner_image_bannerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Google Maps embed URL (src= from the iframe). When set, overrides the auto-generated map.'),
        ),
    ]
