# Generated by Django 6.0.3 on 2026-05-28 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_contentblock_button_url'),
        ('core', '0042_add_map_embed_url_to_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='content_group',
            field=models.ForeignKey(blank=True, help_text='Content group supplying title, body, and button slots for this banner.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='content.contentgroup'),
        ),
        migrations.AddField(
            model_name='panelside',
            name='component',
            field=models.CharField(choices=[('content', 'Content (uses ContentGroup)'), ('map', 'Google Maps Embed'), ('image', 'Full-bleed Image')], default='content', help_text='What this panel side renders.', max_length=20),
        ),
        migrations.AddField(
            model_name='panelside',
            name='content_group',
            field=models.ForeignKey(blank=True, help_text='Content group for this panel side. Only used when component is Content.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_sides', to='content.contentgroup'),
        ),
    ]
