# Generated by Django 6.0.3 on 2026-05-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_banner_panelside_content_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='bg_color',
            field=models.CharField(choices=[('bg-primary', 'Page Background (near-white)'), ('bg-secondary', 'Warm Cream'), ('bg-tertiary', 'Warm Linen'), ('bg-surface', 'Light Panel Surface'), ('bg-surface-raised', 'Raised Panel Surface'), ('white', 'White'), ('accent-red-light', 'Red Tint (light)'), ('gold-light', 'Gold — Pale Tint'), ('gold-bright', 'Gold — Bright'), ('gold-primary', 'Gold — Sandy (brand)'), ('bg-accent', 'Gold — Button/Accent'), ('gold-deep', 'Gold — Deep'), ('dark-gray', 'Dark Warm Gray'), ('steeler-black', 'Near Black'), ('accent-red', 'Brand Red'), ('steeler-gold', 'Bright Yellow Gold'), ('text-accent', 'Gold Accent (text)'), ('text-primary', 'Warm Near-Black (text)'), ('text-secondary', 'Medium Brown (text)'), ('text-tertiary', 'Dark Charcoal (text)'), ('text-heading', 'Near-Black Heading (text)')], default='bg-primary', max_length=50),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_color',
            field=models.CharField(choices=[('bg-primary', 'Page Background (near-white)'), ('bg-secondary', 'Warm Cream'), ('bg-tertiary', 'Warm Linen'), ('bg-surface', 'Light Panel Surface'), ('bg-surface-raised', 'Raised Panel Surface'), ('white', 'White'), ('accent-red-light', 'Red Tint (light)'), ('gold-light', 'Gold — Pale Tint'), ('gold-bright', 'Gold — Bright'), ('gold-primary', 'Gold — Sandy (brand)'), ('bg-accent', 'Gold — Button/Accent'), ('gold-deep', 'Gold — Deep'), ('dark-gray', 'Dark Warm Gray'), ('steeler-black', 'Near Black'), ('accent-red', 'Brand Red'), ('steeler-gold', 'Bright Yellow Gold'), ('text-accent', 'Gold Accent (text)'), ('text-primary', 'Warm Near-Black (text)'), ('text-secondary', 'Medium Brown (text)'), ('text-tertiary', 'Dark Charcoal (text)'), ('text-heading', 'Near-Black Heading (text)')], default='text-primary', max_length=50),
        ),
        migrations.AlterField(
            model_name='bannerbutton',
            name='bg_color',
            field=models.CharField(choices=[('bg-primary', 'Page Background (near-white)'), ('bg-secondary', 'Warm Cream'), ('bg-tertiary', 'Warm Linen'), ('bg-surface', 'Light Panel Surface'), ('bg-surface-raised', 'Raised Panel Surface'), ('white', 'White'), ('accent-red-light', 'Red Tint (light)'), ('gold-light', 'Gold — Pale Tint'), ('gold-bright', 'Gold — Bright'), ('gold-primary', 'Gold — Sandy (brand)'), ('bg-accent', 'Gold — Button/Accent'), ('gold-deep', 'Gold — Deep'), ('dark-gray', 'Dark Warm Gray'), ('steeler-black', 'Near Black'), ('accent-red', 'Brand Red'), ('steeler-gold', 'Bright Yellow Gold'), ('text-accent', 'Gold Accent (text)'), ('text-primary', 'Warm Near-Black (text)'), ('text-secondary', 'Medium Brown (text)'), ('text-tertiary', 'Dark Charcoal (text)'), ('text-heading', 'Near-Black Heading (text)')], default='bg-secondary', max_length=50),
        ),
        migrations.AlterField(
            model_name='bannerbutton',
            name='text_color',
            field=models.CharField(choices=[('bg-primary', 'Page Background (near-white)'), ('bg-secondary', 'Warm Cream'), ('bg-tertiary', 'Warm Linen'), ('bg-surface', 'Light Panel Surface'), ('bg-surface-raised', 'Raised Panel Surface'), ('white', 'White'), ('accent-red-light', 'Red Tint (light)'), ('gold-light', 'Gold — Pale Tint'), ('gold-bright', 'Gold — Bright'), ('gold-primary', 'Gold — Sandy (brand)'), ('bg-accent', 'Gold — Button/Accent'), ('gold-deep', 'Gold — Deep'), ('dark-gray', 'Dark Warm Gray'), ('steeler-black', 'Near Black'), ('accent-red', 'Brand Red'), ('steeler-gold', 'Bright Yellow Gold'), ('text-accent', 'Gold Accent (text)'), ('text-primary', 'Warm Near-Black (text)'), ('text-secondary', 'Medium Brown (text)'), ('text-tertiary', 'Dark Charcoal (text)'), ('text-heading', 'Near-Black Heading (text)')], default='text-primary', max_length=50),
        ),
        migrations.AlterField(
            model_name='panelside',
            name='bg_color',
            field=models.CharField(choices=[('bg-primary', 'Page Background (near-white)'), ('bg-secondary', 'Warm Cream'), ('bg-tertiary', 'Warm Linen'), ('bg-surface', 'Light Panel Surface'), ('bg-surface-raised', 'Raised Panel Surface'), ('white', 'White'), ('accent-red-light', 'Red Tint (light)'), ('gold-light', 'Gold — Pale Tint'), ('gold-bright', 'Gold — Bright'), ('gold-primary', 'Gold — Sandy (brand)'), ('bg-accent', 'Gold — Button/Accent'), ('gold-deep', 'Gold — Deep'), ('dark-gray', 'Dark Warm Gray'), ('steeler-black', 'Near Black'), ('accent-red', 'Brand Red'), ('steeler-gold', 'Bright Yellow Gold'), ('text-accent', 'Gold Accent (text)'), ('text-primary', 'Warm Near-Black (text)'), ('text-secondary', 'Medium Brown (text)'), ('text-tertiary', 'Dark Charcoal (text)'), ('text-heading', 'Near-Black Heading (text)')], default='bg-primary', help_text='Background color. For image panels, shows while image loads.', max_length=50),
        ),
        migrations.AlterField(
            model_name='panelside',
            name='button_bg_color',
            field=models.CharField(blank=True, choices=[('bg-primary', 'Page Background (near-white)'), ('bg-secondary', 'Warm Cream'), ('bg-tertiary', 'Warm Linen'), ('bg-surface', 'Light Panel Surface'), ('bg-surface-raised', 'Raised Panel Surface'), ('white', 'White'), ('accent-red-light', 'Red Tint (light)'), ('gold-light', 'Gold — Pale Tint'), ('gold-bright', 'Gold — Bright'), ('gold-primary', 'Gold — Sandy (brand)'), ('bg-accent', 'Gold — Button/Accent'), ('gold-deep', 'Gold — Deep'), ('dark-gray', 'Dark Warm Gray'), ('steeler-black', 'Near Black'), ('accent-red', 'Brand Red'), ('steeler-gold', 'Bright Yellow Gold'), ('text-accent', 'Gold Accent (text)'), ('text-primary', 'Warm Near-Black (text)'), ('text-secondary', 'Medium Brown (text)'), ('text-tertiary', 'Dark Charcoal (text)'), ('text-heading', 'Near-Black Heading (text)')], default='bg-secondary', max_length=50),
        ),
        migrations.AlterField(
            model_name='panelside',
            name='button_text_color',
            field=models.CharField(blank=True, choices=[('bg-primary', 'Page Background (near-white)'), ('bg-secondary', 'Warm Cream'), ('bg-tertiary', 'Warm Linen'), ('bg-surface', 'Light Panel Surface'), ('bg-surface-raised', 'Raised Panel Surface'), ('white', 'White'), ('accent-red-light', 'Red Tint (light)'), ('gold-light', 'Gold — Pale Tint'), ('gold-bright', 'Gold — Bright'), ('gold-primary', 'Gold — Sandy (brand)'), ('bg-accent', 'Gold — Button/Accent'), ('gold-deep', 'Gold — Deep'), ('dark-gray', 'Dark Warm Gray'), ('steeler-black', 'Near Black'), ('accent-red', 'Brand Red'), ('steeler-gold', 'Bright Yellow Gold'), ('text-accent', 'Gold Accent (text)'), ('text-primary', 'Warm Near-Black (text)'), ('text-secondary', 'Medium Brown (text)'), ('text-tertiary', 'Dark Charcoal (text)'), ('text-heading', 'Near-Black Heading (text)')], default='text-primary', max_length=50),
        ),
        migrations.AlterField(
            model_name='panelside',
            name='text_color',
            field=models.CharField(choices=[('bg-primary', 'Page Background (near-white)'), ('bg-secondary', 'Warm Cream'), ('bg-tertiary', 'Warm Linen'), ('bg-surface', 'Light Panel Surface'), ('bg-surface-raised', 'Raised Panel Surface'), ('white', 'White'), ('accent-red-light', 'Red Tint (light)'), ('gold-light', 'Gold — Pale Tint'), ('gold-bright', 'Gold — Bright'), ('gold-primary', 'Gold — Sandy (brand)'), ('bg-accent', 'Gold — Button/Accent'), ('gold-deep', 'Gold — Deep'), ('dark-gray', 'Dark Warm Gray'), ('steeler-black', 'Near Black'), ('accent-red', 'Brand Red'), ('steeler-gold', 'Bright Yellow Gold'), ('text-accent', 'Gold Accent (text)'), ('text-primary', 'Warm Near-Black (text)'), ('text-secondary', 'Medium Brown (text)'), ('text-tertiary', 'Dark Charcoal (text)'), ('text-heading', 'Near-Black Heading (text)')], default='text-primary', max_length=50),
        ),
    ]
