# Generated by Django 6.0.3 on 2026-05-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_banner_bg_color_alter_banner_text_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='bg_color',
            field=models.CharField(choices=[('bg-primary', 'Page Background (near-white)'), ('bg-secondary', 'Warm Cream'), ('bg-tertiary', 'Warm Linen'), ('bg-surface', 'Light Panel Surface'), ('bg-surface-raised', 'Raised Panel Surface'), ('white', 'White'), ('accent-red-light', 'Red Tint')], default='bg-primary', max_length=50),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_color',
            field=models.CharField(choices=[('text-primary', 'Warm Near-Black'), ('text-secondary', 'Medium Brown'), ('text-tertiary', 'Dark Charcoal'), ('text-heading', 'Near-Black Heading'), ('text-accent', 'Gold Accent'), ('steeler-black', 'Black'), ('white', 'White')], default='text-primary', max_length=50),
        ),
        migrations.AlterField(
            model_name='bannerbutton',
            name='bg_color',
            field=models.CharField(choices=[('bg-primary', 'Page Background (near-white)'), ('bg-secondary', 'Warm Cream'), ('bg-tertiary', 'Warm Linen'), ('bg-surface', 'Light Panel Surface'), ('bg-surface-raised', 'Raised Panel Surface'), ('white', 'White'), ('accent-red-light', 'Red Tint')], default='bg-secondary', max_length=50),
        ),
        migrations.AlterField(
            model_name='bannerbutton',
            name='text_color',
            field=models.CharField(choices=[('text-primary', 'Warm Near-Black'), ('text-secondary', 'Medium Brown'), ('text-tertiary', 'Dark Charcoal'), ('text-heading', 'Near-Black Heading'), ('text-accent', 'Gold Accent'), ('steeler-black', 'Black'), ('white', 'White')], default='text-primary', max_length=50),
        ),
        migrations.AlterField(
            model_name='panelside',
            name='bg_color',
            field=models.CharField(choices=[('bg-primary', 'Page Background (near-white)'), ('bg-secondary', 'Warm Cream'), ('bg-tertiary', 'Warm Linen'), ('bg-surface', 'Light Panel Surface'), ('bg-surface-raised', 'Raised Panel Surface'), ('white', 'White'), ('accent-red-light', 'Red Tint')], default='bg-primary', help_text='Background color. For image panels, shows while image loads.', max_length=50),
        ),
        migrations.AlterField(
            model_name='panelside',
            name='button_bg_color',
            field=models.CharField(blank=True, choices=[('bg-primary', 'Page Background (near-white)'), ('bg-secondary', 'Warm Cream'), ('bg-tertiary', 'Warm Linen'), ('bg-surface', 'Light Panel Surface'), ('bg-surface-raised', 'Raised Panel Surface'), ('white', 'White'), ('accent-red-light', 'Red Tint')], default='bg-secondary', max_length=50),
        ),
        migrations.AlterField(
            model_name='panelside',
            name='button_text_color',
            field=models.CharField(blank=True, choices=[('text-primary', 'Warm Near-Black'), ('text-secondary', 'Medium Brown'), ('text-tertiary', 'Dark Charcoal'), ('text-heading', 'Near-Black Heading'), ('text-accent', 'Gold Accent'), ('steeler-black', 'Black'), ('white', 'White')], default='text-primary', max_length=50),
        ),
        migrations.AlterField(
            model_name='panelside',
            name='text_color',
            field=models.CharField(choices=[('text-primary', 'Warm Near-Black'), ('text-secondary', 'Medium Brown'), ('text-tertiary', 'Dark Charcoal'), ('text-heading', 'Near-Black Heading'), ('text-accent', 'Gold Accent'), ('steeler-black', 'Black'), ('white', 'White')], default='text-primary', max_length=50),
        ),
    ]
