# Generated by Django 6.0.3 on 2026-05-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_banner_bg_color_alter_banner_text_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='doordash_url',
            field=models.URLField(blank=True, help_text='DoorDash store page URL.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='grubhub_url',
            field=models.URLField(blank=True, help_text='Grubhub store page URL.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ubereats_url',
            field=models.URLField(blank=True, help_text='Uber Eats store page URL.'),
        ),
    ]
