# Generated by Django 6.0.3 on 2026-05-28 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_sitesettings_delivery_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='content',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title',
        ),
        migrations.RemoveField(
            model_name='panelside',
            name='button_bg_color',
        ),
        migrations.RemoveField(
            model_name='panelside',
            name='button_href',
        ),
        migrations.RemoveField(
            model_name='panelside',
            name='button_label',
        ),
        migrations.RemoveField(
            model_name='panelside',
            name='button_text_color',
        ),
        migrations.RemoveField(
            model_name='panelside',
            name='content_slot',
        ),
        migrations.RemoveField(
            model_name='panelside',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='panelside',
            name='title',
        ),
        migrations.DeleteModel(
            name='BannerButton',
        ),
    ]
