# Generated by Django 5.0.14 on 2026-02-17 02:06

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color_code', models.CharField(default='#3B82F6', help_text='Hex color code for displaying promotions (e.g., #FF5733)', max_length=7)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='promotions/category_icons/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promotion Category',
                'verbose_name_plural': 'Promotion Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('short_description', models.CharField(help_text='Brief summary for promotion listings', max_length=300)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(help_text='Full promotion description with details')),
                ('featured_image', models.ImageField(blank=True, help_text='Main promotion image', null=True, upload_to='promotions/featured/')),
                ('image_alt_text', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(help_text='Promotion start date')),
                ('start_time', models.TimeField(blank=True, help_text='Promotion start time (optional)', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Promotion end date (optional)', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Promotion end time (optional)', null=True)),
                ('recurrence_type', models.CharField(choices=[('none', 'Does Not Repeat'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', help_text='Does this promotion repeat?', max_length=20)),
                ('recurrence_end_date', models.DateField(blank=True, help_text='When does the recurring promotion end?', null=True)),
                ('has_registration', models.BooleanField(default=False, help_text='Does this promotion require registration?')),
                ('max_capacity', models.PositiveIntegerField(blank=True, help_text='Maximum number of attendees (leave blank for unlimited)', null=True)),
                ('current_registrations', models.PositiveIntegerField(default=0, help_text='Current number of registrations')),
                ('registration_deadline', models.DateTimeField(blank=True, help_text='Last date/time for registration', null=True)),
                ('is_free', models.BooleanField(default=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price per person (if applicable)', max_digits=8, null=True)),
                ('contact_email', models.EmailField(blank=True, help_text='Contact email for promotion inquiries', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone for promotion inquiries', max_length=20)),
                ('external_url', models.URLField(blank=True, help_text='External registration or information URL')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this promotion prominently on the homepage')),
                ('is_special', models.BooleanField(default=False, help_text='Mark as special/exclusive promotion')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('published_date', models.DateTimeField(blank=True, help_text='When this promotion was published', null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for search engines', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='promotions.promotioncategory')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['start_date', 'start_time', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PromotionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='promotions/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='promotions.promotion')),
            ],
            options={
                'verbose_name': 'Promotion Image',
                'verbose_name_plural': 'Promotion Images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['start_date', 'status'], name='promotions_even_start_d_9e40f1_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['is_featured', 'status'], name='promotions_even_is_feat_ff8c54_idx'),
        ),
    ]
