# Generated by Django 6.0.3 on 2026-05-27 19:37

import apps.media.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='Auto-generated from name.', unique=True)),
                ('description', models.CharField(blank=True, help_text='Shown as a subtitle on the public gallery page.', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Controls tab order on the public gallery. Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='False = hidden from the public gallery. Still visible in the staff portal.')),
                ('is_gallery_visible', models.BooleanField(default=True, help_text='False = internal library category only (e.g. Banner Images). Never shown as a tab on the public gallery page.')),
            ],
            options={
                'verbose_name': 'Media Category',
                'verbose_name_plural': 'Media Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Human-readable library name — staff-entered, renameable. E.g. 'Burger Hero Shot Summer 2025'. Separate from caption, which is public-facing.", max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from name. Used internally, not in URLs.', max_length=220, unique=True)),
                ('owner_type', models.CharField(choices=[('staff', 'Staff'), ('member', 'Member submission')], default='staff', help_text='Staff items are eligible for site-wide use. Member submissions go through moderation and never appear in staff pickers.', max_length=10)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('file', models.ImageField(blank=True, help_text="Used when media_type='image'. Leave blank for video items.", max_length=500, upload_to=apps.media.models.media_upload_path)),
                ('video_url', models.URLField(blank=True, help_text="Used when media_type='video'. GLightbox auto-detects YouTube, Vimeo, TikTok, and direct MP4 URLs.")),
                ('alt_text', models.CharField(blank=True, help_text='Accessibility alt text. Also used as a fallback caption.', max_length=255)),
                ('caption', models.CharField(blank=True, help_text='Public-facing caption shown in the gallery lightbox.', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order within category on the public gallery.')),
                ('is_published', models.BooleanField(default=False, help_text='False = not shown on the public gallery. Staff items default to False and must be explicitly published.')),
                ('is_approved', models.BooleanField(default=True, help_text='Staff items: always True. Member submissions: starts False, set True by staff after review.')),
                ('is_flagged', models.BooleanField(default=False, help_text='Moderation flag — set True to queue for staff review.')),
                ('flagged_reason', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, help_text='Primary category for gallery display.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='media.mediacategory')),
                ('member', models.ForeignKey(blank=True, help_text="Populated for member submissions only (owner_type='member').", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_submissions', to='members.sohomember')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='Staff user who uploaded this item. Null for files imported from disk.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media Item',
                'verbose_name_plural': 'Media Items',
                'ordering': ['category__display_order', 'display_order', 'name'],
            },
        ),
    ]
