# Generated by Django 6.0.3 on 2026-05-20 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('menu', '0007_replace_show_on_homepage_with_homepage_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='menu_item',
            field=models.ForeignKey(blank=True, help_text='Link to a menu item to show this photo on the menu card and modal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_items', to='menu.menuitem'),
        ),
    ]
