# Generated by Django 6.0.3 on 2026-05-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_add_menu_item_link_to_galleryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(blank=True, max_length=500, upload_to='gallery/'),
        ),
    ]
